In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [12]:
df = pd.read_csv("processed_data.csv", = False)

TypeError: read_csv() got an unexpected keyword argument 'index'

In [3]:
df

,Unnamed: 0,name,album,artist,release_date,length,popularity,danceability,acousticness,energy,instrumentalness,liveness,loudness,speechiness,tempo,time_signature
0,0,You Need To Calm Down,Lover,Taylor Swift,2019-08-23,171360,84,0.771,0.00929,0.671,0.000000,0.0637,-5.617,0.0553,85.026,4
1,1,"thank u, next","thank u, next",Ariana Grande,2019-02-08,207320,82,0.717,0.22900,0.653,0.000000,0.1010,-5.634,0.0658,106.966,4
2,2,EARFQUAKE,IGOR,"Tyler, The Creator",2019-05-17,190066,82,0.554,0.23000,0.498,0.000006,0.7950,-8.866,0.0685,79.635,4
3,3,Lose You To Love Me,Rare,Selena Gomez,2020-01-10,206458,82,0.488,0.55600,0.343,0.000000,0.2100,-8.985,0.0436,102.819,4
4,4,High Hopes,Pray for the Wicked,Panic! At The Disco,2018-06-22,190946,82,0.579,0.19300,0.904,0.000000,0.0640,-2.729,0.0618,82.014,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2787,3224,Holy (feat. Chance The Rapper),Holy,Justin Bieber,2020-09-18,212093,72,0.673,0.19600,0.704,0.000000,0.0898,-8.056,0.3600,86.919,4
2788,3225,Don't You Worry About Me,Don't You Worry About Me,Bad Boy Chiller Crew,2021-02-18,220173,52,0.760,0.10300,0.889,0.000000,0.3480,-3.092,0.0793,129.961,4
2789,3226,The Business,The Business,Tiësto,2020-09-16,164000,79,0.798,0.41400,0.620,0.019200,0.1120,-7.079,0.2320,120.031,4
2790,3227,Return of the Mack,Return of the Mack,Mark Morrison,1996-04-22,213093,78,0.715,0.00631,0.833,0.000000,0.1640,-5.379,0.1080,95.487,4
2791,3228,Don't Play,Don't Play,Anne-Marie,2021-01-15,188580,56,0.695,0.08890,0.784,0.000000,0.0843,-6.564,0.0402,128.031,4

In [10]:
onehot = OneHotEncoder(handle_unknown='ignore',sparse_output= False).set_output(transform = 'pandas')

onehot_encoded_artist = onehot.fit_transform(df[["artist"]])
print(type(onehot_encoded_artist))
onehot_encoded_artist

<class 'pandas.core.frame.DataFrame'>

,artist_(G)I-DLE,artist_10cm,artist_1nonly,artist_21 Savage,artist_220 KID,artist_24kGoldn,artist_2AM,artist_2NE1,artist_2PM,artist_310babii,...,artist_jjvsdawrld,artist_nezsa,artist_raph,artist_shy taupe,artist_thuy,artist_tuki.,artist_vaultboy,artist_waykap,artist_will.i.am,artist_фрози
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2787,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2788,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2789,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2790,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2791,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
df.artist.value_counts()

artist
Various Artists             55
Twenty One Pilots           51
Taylor Swift                29
Drake                       27
The Weeknd                  24
                            ..
Turma do Pagode              1
Fernando & Sorocaba          1
Lilly Wood and The Prick     1
Valesca Popozuda             1
Mark Morrison                1
Name: count, Length: 1244, dtype: int64

In [6]:
pd.get_dummies(df.artist)

,(G)I-DLE,10cm,1nonly,21 Savage,220 KID,24kGoldn,2AM,2NE1,2PM,310babii,...,jjvsdawrld,nezsa,raph,shy taupe,thuy,tuki.,vaultboy,waykap,will.i.am,фрози
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2787,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2788,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2789,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2790,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2791,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [11]:
df

,Unnamed: 0,name,album,artist,release_date,length,popularity,danceability,acousticness,energy,instrumentalness,liveness,loudness,speechiness,tempo,time_signature
0,0,You Need To Calm Down,Lover,Taylor Swift,2019-08-23,171360,84,0.771,0.00929,0.671,0.000000,0.0637,-5.617,0.0553,85.026,4
1,1,"thank u, next","thank u, next",Ariana Grande,2019-02-08,207320,82,0.717,0.22900,0.653,0.000000,0.1010,-5.634,0.0658,106.966,4
2,2,EARFQUAKE,IGOR,"Tyler, The Creator",2019-05-17,190066,82,0.554,0.23000,0.498,0.000006,0.7950,-8.866,0.0685,79.635,4
3,3,Lose You To Love Me,Rare,Selena Gomez,2020-01-10,206458,82,0.488,0.55600,0.343,0.000000,0.2100,-8.985,0.0436,102.819,4
4,4,High Hopes,Pray for the Wicked,Panic! At The Disco,2018-06-22,190946,82,0.579,0.19300,0.904,0.000000,0.0640,-2.729,0.0618,82.014,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2787,3224,Holy (feat. Chance The Rapper),Holy,Justin Bieber,2020-09-18,212093,72,0.673,0.19600,0.704,0.000000,0.0898,-8.056,0.3600,86.919,4
2788,3225,Don't You Worry About Me,Don't You Worry About Me,Bad Boy Chiller Crew,2021-02-18,220173,52,0.760,0.10300,0.889,0.000000,0.3480,-3.092,0.0793,129.961,4
2789,3226,The Business,The Business,Tiësto,2020-09-16,164000,79,0.798,0.41400,0.620,0.019200,0.1120,-7.079,0.2320,120.031,4
2790,3227,Return of the Mack,Return of the Mack,Mark Morrison,1996-04-22,213093,78,0.715,0.00631,0.833,0.000000,0.1640,-5.379,0.1080,95.487,4
2791,3228,Don't Play,Don't Play,Anne-Marie,2021-01-15,188580,56,0.695,0.08890,0.784,0.000000,0.0843,-6.564,0.0402,128.031,4